---
- name: Setup Vprofile stack
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Import VPC setup variable
      include_vars: vars/vpc-output_vars

    - name: Import vprofile setup variable
      include_vars: vars/vprostacksetup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: Save private key into loginkey_vpro.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed

    - name: Security Group for Load Balancer
      amazon.aws.ec2_group:
        name: vproELB_sg
        description: Security Group for Load Balancer
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBsg_out

    - name: Security Group for EC2 stack
      amazon.aws.ec2_group:
        name: vproStack-sg
        description: Security Group for EC2 stack
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ vproELBsg_out.group_id }}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ BastionSGid }}"
      register: vproStackSG_out
    
    - name: Update Security Group with its own sg id
      amazon.aws.ec2_group:
        name: vproStack-sg
        description: Allow port 22 from everywhere and all ports within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{vproStackSG_out.group_id}}"