---
- name: Setup Vprofile stack
  hosts: localhost
  connections: local
  gather_facts: false
  tasks:

    - name: Import VPC setup variable
      import_vars: vars/output_vars

    - name: Import vprofile setup variable
      import_vars: vars/vprostacksetup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: Save private key into loginkey_vpro.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed