---
- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  gather_facts: yes
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - curl
        - gnupg
        - apt-transport-https
        - lsb-release
        - ca-certificates

    - name: Add RabbitMQ signing key (PackageCloud)
      apt_key:
        url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
        state: present

    - name: Add RabbitMQ APT repository (PackageCloud)
      apt_repository:
        repo: "deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ ansible_distribution_release }} main"
        state: present

    - name: Add Erlang repository (Cloudsmith)
      apt_repository:
        repo: "deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ ansible_distribution_release }} main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install RabbitMQ Server
      apt:
        name: rabbitmq-server
        state: present
      tags: package

    - name: Start and enable RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Configure RabbitMQ to allow remote login (disable loopback restriction)
      copy:
        dest: /etc/rabbitmq/rabbitmq.config
        content: |
          [{rabbit, [{loopback_users, []}]}].
      notify: Restart RMQ

    - name: Create RabbitMQ admin user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify: Restart RMQ

    - name: Enable the RabbitMQ management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify: Restart RMQ

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted
